{{- if .Values.mongoDBConfiguration }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-additional-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
data:
  mongo.yaml: {{ .Values.mongoDBConfiguration | toYaml | indent 2 | trim }}
{{- end }}