{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace (print .Release.Name "-standalone-" .Release.Name "-standalone-0")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.password | default (randAlphaNum 20) | b64enc }}
{{- end }}