{{- if eq .Values.externalService.enabled true }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-headless
{{- if .Values.externalService.annotations }}
  annotations:
{{ toYaml .Values.externalService.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: middleware
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-standalone
    mongodb_setup: standalone
    role: standalone
  ports:
    - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
{{- if .Values.externalService.annotations }}
  annotations:
{{ toYaml .Values.externalService.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: middleware
spec:
  type: {{ .Values.externalService.serviceType }}
  selector:
    app: {{ .Release.Name }}-standalone
    mongodb_setup: standalone
    role: standalone
  ports:
    - protocol: TCP
      port: {{ .Values.externalService.port }}
      targetPort: 27017
      name: client
{{- end }}